services:
  percona:
    image: percona/percona-server:8.0.40-aarch64
    container_name: ps_mysql
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: bob
      MYSQL_PASSWORD: secretbob
    volumes:
      - supply_chain_data:/var/lib/mysql
      - ./cfg/my.cnf:/etc/my.cnf
    networks:
      - ps_mysql_network
volumes:
  supply_chain_data:

networks:
  ps_mysql_network:
    driver: bridge
