/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface BillOfMaterials {
  bom_id: Generated<number>;
  component_product_id: number;
  finished_product_id: number;
  quantity_required: number;
}

export interface Customer {
  address: string | null;
  created_at: Generated<Date | null>;
  customer_id: Generated<number>;
  email: string;
  name: string | null;
  phone_number: string | null;
}

export interface Inventory {
  inventory_id: Generated<number>;
  last_update: Generated<Date | null>;
  product_id: number;
  quantity: number;
  warehouse_id: number;
}

export interface ManufacturingOrder {
  finished_product_id: number;
  manufacturing_order_id: Generated<number>;
  production_end_date: Date | null;
  production_start_date: Generated<Date | null>;
  quantity_to_produce: number;
  status: Generated<"Canceled" | "Completed" | "In Progress" | "Pending" | null>;
}

export interface OrderDetails {
  order_detail_id: Generated<number>;
  order_id: number;
  price: Decimal;
  product_id: number;
  quantity: number;
  total_price: Decimal | null;
}

export interface Orders {
  customer_amount: Decimal | null;
  customer_id: number;
  order_date: Generated<Date | null>;
  order_id: Generated<number>;
  status: Generated<"Canceled" | "Delivered" | "Pending" | "Shipped" | null>;
}

export interface Product {
  category: string | null;
  is_finished_product: Generated<number | null>;
  name: string;
  price: Decimal;
  product_id: Generated<number>;
  supplier_id: number | null;
}

export interface Shipment {
  delivery_date: Date | null;
  order_id: number;
  shipment_date: Generated<Date | null>;
  shipment_id: Generated<number>;
  status: Generated<"Delivered" | "In Transit" | "Returned" | null>;
  warehouse_id: number;
}

export interface Supplier {
  brand_name: string;
  created_at: Generated<Date | null>;
  location: string | null;
  supplier_id: Generated<number>;
  supplier_name: string;
  support_email: string;
  support_phone: number | null;
}

export interface Warehouse {
  capacity: number;
  created_at: Generated<Date | null>;
  location: string;
  name: string | null;
  warehouse_id: Generated<number>;
}

export interface DB {
  BillOfMaterials: BillOfMaterials;
  Customer: Customer;
  Inventory: Inventory;
  ManufacturingOrder: ManufacturingOrder;
  OrderDetails: OrderDetails;
  Orders: Orders;
  Product: Product;
  Shipment: Shipment;
  Supplier: Supplier;
  Warehouse: Warehouse;
}
